### PR TITLE
Various bug fixes

### LINKED ISSUE #15: Conditions not saving the value field
The ConditionBuilder formwidget changes the $_POST superglobal in [L351](https://github.com/rainlab/notify-plugin/blob/master/formwidgets/ConditionBuilder.php#L351)  and [L356](https://github.com/rainlab/notify-plugin/blob/master/formwidgets/ConditionBuilder.php#L356) but due to [this](https://github.com/octobercms/library/commit/fd839047c2d7757f225a8ed60673ca8a20fe7df4) change in https://github.com/octobercms/library, the $_POST superglobal can't be changed directly anymore. So, the value field is not saved.  [This](https://github.com/rainlab/translate-plugin/pull/463) could be changed here too in order to fix it:

Insted of:

`$_POST['condition_data'] = $cache;`

Now should be:

```
$requestData = Request::all();
array_set($requestData, 'condition_data' , $cache);
Request::merge($requestData);        
```

### PR DESCRIPTION
**Pull request by LukeTowers**
Replaces #16. Fixes #15, #10

### CODE REVIEW

**Comment by bkrajendra** [comment]
with latest OCMS build and UserPlus plugin, im still getting this error.

**Comment by bkrajendra** [comment]
My issue got resolved after assigning email template to rule.
Or might be some other tinkering. But it stopped now.

**Comment by LukeTowers** [comment]
@bkrajendra if you can reproduce it on a fresh october install using the latest version of the plugin then please post the reproduction instructions here.

**Comment by bkrajendra** [comment]
I got this issue on fresh latest install of plugin and october. Only got resolved when i assigned email template.

**Comment by LukeTowers** [comment]
@bkrajendra please submit a new issue then with the full step by step of what you did from installation to the error happening

**Pull request merged**
