### PR TITLE
Expanded Localization Lang

### PR DESCRIPTION
**Pull request by ZhiweiWu0425**

### CODE REVIEW

**Comment by daftspunk** [comment]
Looks fine, except it currently conflicts with the master branch.

**Comment by ZhiweiWu0425** [comment]
Conflict has been resolved. Be sure to review the code section to prevent unexpected errors.

**Comment by daftspunk** [comment]
Thanks!

**Comment by daftspunk** [comment]
I'm sorry this created too many problems in the code. It has switched to the newer method of translation.

This file should be translated instead: https://github.com/rainlab/notify-plugin/blob/master/lang/zh-cn.json

The old file is here: https://github.com/rainlab/notify-plugin/blob/feature/chinese-translation/lang/zh-cn/lang.php

**Pull request merged**
